//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Comments = new HashSet<Comment>();
            this.EventTags = new HashSet<EventTag>();
            this.EventImages = new HashSet<EventImage>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public string AuthorId { get; set; }
        public string Description { get; set; }
        public bool IsPublic { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Zip { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<EventTag> EventTags { get; set; }
        public virtual ICollection<EventImage> EventImages { get; set; }
    }
}
